Repository davidsbond/forcelog, pull requests merged in 2019-01, with the labels that each got.

#11 Added support for logging System.RestResponse and Messaging.SendEmailResult
  README.md
  src/ForceLog.cls
  src/tests/ForceLogTest.cls
Labels: enhancement

#15 Removed docs from README in favour of GitHub wiki
  README.md
Labels: documentation

#12 Added logging support for Database.QueryLocator
  src/ForceLog.cls
  src/tests/ForceLogTest.cls
Labels: enhancement

#13 Added logging support for Database.MergeResult
  pmd.xml
  src/ForceLog.cls
  src/tests/ForceLogTest.cls
Labels: enhancement

#17 Added support for log hooks
  src/ForceLog.cls
  src/tests/ForceLogTest.cls
Labels: enhancement

#16 Clear the internal log buffer on dispose.
  src/ForceLog.cls
Labels: bug
